### ISSUE TITLE
You somehow forgot to version your code before BC ?

### ISSUE THREAD

**Issue by tomasstrejcek** [heureka/overeno-zakazniky#7]
Sorry, but this just isnt nice of you..

For all of you who dont have time to fix this right now, one of possible solutions is to update your composer json to `  "heureka/overenozakazniky": "dev-master#9c737335708b99090d5dcf6b59c141a423d0a50d",
`

**Comment by grongor** [comment]
Sorry for the inconvenience. As I stated in the "first release" (https://github.com/heureka/overeno-zakazniky/releases/tag/v0.1), the library is pretty old and therefore isn't up to todays standards (like having good tags without BC breaks).

This is why I tagged the old version as v0.1 prior to any BC changes.

Anyway it is discouraged to use `"package/name": "dev-master"` in any projects (except for rare special cases) because there is no way for library contributors to not introduce BC changes. If the library doesn't provide tagged versions (it is very bad practise, we are sorry about that - it's gonna change now) you should always use specific commit, as you mentioned.

So please if anyone else uses `"heureka/overenozakazniky": "dev-master"` then please update this dependency to `"heureka/overenozakazniky": "0.1"`.

Thank you and I'm sorry again if that caused you any troubles.
